TITLE="GTA FiveM Athena"
WINDOW_WIDTH = 300
WINDOW_HEIGHT = 200

HEADER_CROP_SCREEN_DETECT = "Crop your screen for focus."
TESSERACT_CMD_PATH ='C:\\Program Files\\Tesseract-OCR\\tesseract.exe'

# KEY BIND
FOOD_KEYBIND = '4'
DRINK_KEYBIND = '5'
OPEN_INVENTORY = 'f2'
OPEN_CAR_INVENTORY = 'l'
ROD_FISH = '1'
FARM_MANAGER = '2'
UNLOCK_CAR = 'u'


# STATIC POSITION
FISHING_RANDOM_CHAR_POS_X = 900
FISHING_RANDOM_CHAR_POS_Y = 742
FISHING_RANDOM_CHAR_WIDTH = 30
FISHING_RANDOM_CHAR_HEIGHT = 30

AMOUNT_TEXT_INVENTORY_POS_X = 955
AMOUNT_TEXT_INVENTORY_POS_Y = 545

# STATIC POSITION NORMAL
SEARCH_INVENTORY_POS_X = 780
SEARCH_INVENTORY_POS_Y = 300

FIRST_ITEM_POS_X = 750
FIRST_ITEM_POS_Y = 370

FIRST_FIND_ITEM_POS_X = 1000
FIRST_FIND_ITEM_POS_Y = 360

INVENTORY_BIN_POS_X = 1300
INVENTORY_BIN_POS_Y = 370

INVENTORY_MAX_POS_X = 1035
INVENTORY_MAX_POS_Y = 545

INVENTORY_CONFIRM_POS_X = 1000
INVENTORY_CONFIRM_POS_Y = 580

# STATIC POSITION IN CAR
SEARCH_CAR_INVENTORY_POS_X = 650
SEARCH_CAR_INVENTORY_POS_Y = 300

FIRST_ITEM_CAR_POS_X = 625
FIRST_ITEM_CAR_POS_Y = 365

FIRST_FIND_ITEM_CAR_POS_X = 1000
FIRST_FIND_ITEM_CAR_POS_Y = 365


# ITEM
ITEM_JUNK_NAME = '-pt' # ขยะ
ITEM_FISHING_BAIT_NAME = 'gspnjv9dx]k' # เหยื่อตกปลา
ITEM_OCTOPUS_NAME = 'x]ks,7d' # ปลาหมึก
ITEM_TUNA_NAME = 'ojk' # ปลาทูน่า
ITEM_CAT_NAME = 'ohv\'c,;' # น้องแมว
